apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    #
spec:
  type: NodePort
  ports:
    ports:
      targetPort: 80
      port: 80
      nodePort: 30008
      #
