apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-04-07T02:15:53Z"
  generation: 1
  name: frontend
  namespace: default
  resourceVersion: "1125"
  uid: 7490c3fb-a532-49c5-b9e7-f15e4774e178
spec:
  minReadySeconds: 20
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: webapp
    spec:
      containers:
        - image: kodekloud/webapp-color:v1
          imagePullPolicy: IfNotPresent
          name: simple-webapp
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
    - lastTransitionTime: "2024-04-07T02:16:19Z"
      lastUpdateTime: "2024-04-07T02:16:19Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-04-07T02:15:54Z"
      lastUpdateTime: "2024-04-07T02:16:19Z"
      message: ReplicaSet "frontend-685dfcc44" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4